### ISSUE TITLE
How to install cv4pve-diag

### ISSUE THREAD

**Issue by eliyahuadam** [Corsinvest/cv4pve-diag#1]
Hello,

How to install cv4pve-diag after unziping on Proxmox cli?

Thanks.

**Comment by franklupo** [comment]
Hi,
download from release the zip file specific os.
https://github.com/Corsinvest/cv4pve-diag/releases

Best regards

**Comment by eliyahuadam** [comment]
Hello franklupo,
Linux version has been unzipped but the commands not found.
What i missing?

![image](https://user-images.githubusercontent.com/68185622/87286829-04d69680-c502-11ea-8a2f-0804e487978d.png)



Many thanks.

**Comment by franklupo** [comment]
Hi,
download from https://github.com/Corsinvest/cv4pve-diag/releases/tag/v1.2.1
and select your os.

Unzip ad execute

**Comment by eliyahuadam** [comment]
Hi franklupo,
How to execute?
Can you sand please the exactly commands ?

Thanks.

**Comment by franklupo** [comment]
HI,
use --help show comamnd.

see documetation

Best regards
