### ISSUE TITLE
CV4PVE-DIAG Windows Command Syntax

### ISSUE THREAD

**Issue by kenrmayfield** [Corsinvest/cv4pve-diag#10]
Frank

On the Code Page, you might want too show an Example Syntax for Windows.  In Windows when using the  cv4pve-diag [command] [options] Syntax,  it has too be  cv4pve-diag [options] [command].  The [Command] has to be last in the Syntax Chain.   

If not, you will get the Errors below:
C:\test\cv4pvediagx64>cv4pve-diag execute --output=Text --host=10.0.1.1 --username=root@pam --password=password
Unrecognized command or argument '--output=Text'.
Unrecognized command or argument '--host=10.0.1.1'.
Unrecognized command or argument '--username=root@pam'.
Unrecognized command or argument '--password=password'.

The Syntax for the Command for Windows in the Syntax should be:
cv4pve-diag  --output=  --host=  --username=  --password=  [Command]

Example:
cv4pve-diag --output=Text --host=10.0.1.1 --username=root@pam --password=password execute

Also Inform the Windows Users there is a Slight Delay when using the Program due to Processing the Information.
Some Windows Users might think the Program is not working because there is no immediate output.

**Comment by franklupo** [comment]
Hi,
what do you suggest to do?

Best regards

**Comment by kenrmayfield** [comment]
@matteocv

Frank,

1. **Add the Syntax to the **Main Page** for CV4PVE-Diag on GitHub:**
https://github.com/Corsinvest/cv4pve-diag

2. **Also Update the Syntax on CV4PVE-Diags **Banner Page** that shows when you run the Program:**
![image](https://github.com/Corsinvest/cv4pve-diag/assets/89940641/a496f8d5-9422-4183-a76a-a62b60f97af4)

**Comment by franklupo** [comment]
would you create a pull request?

**Comment by kenrmayfield** [comment]
@matteocv

Frank

I have Completed the Pull Request

**Comment by kenrmayfield** [comment]
@matteocv

Frank,

For some Reason the Changes I made too the Banner Logo Command Section did not Update.

I did another Pull Request.  

The Command Syntax for USAGE: should Read: cv4pve-diag [options] [command]

Kenneth

**Comment by franklupo** [comment]
The output is generated by the library that manages the options of command line. I can't change it.

**Comment by kenrmayfield** [comment]
@matteocv

Frank,

I have Update the README.md File with the Corrections.   I did a Pull 
Request.  I just need you too Upload
the Updated README.md.

Kenneth

**Comment by franklupo** [comment]
Hi,
The output "[command] [options]" is generated by the library that manages the options of command line. I can't change it.

Best regards

**Comment by kenrmayfield** [comment]
@matteocv

Frank,


Just asking..........why can you not Upload the New Readme I created?

**Comment by franklupo** [comment]
Becose the text you have changed is output of help command (--help). This is generate automaticaly from other library.

**Comment by kenrmayfield** [comment]
@matteocv

Frank,

I understand what you are stating.  So are you saying even though **I have Updated the HELP Command(USAGE:)** and even if you do Upload the Readme with the Updated HELP Command(USAGE:)...............the HELP Command(USAGE:) that I have Updated via Vi Editor will not change?

**Comment by franklupo** [comment]
the one you changed works but last one doesn't

**Comment by kenrmayfield** [comment]
@matteocv,

Frank,

What do you mean?  I am not understanding.

**Comment by franklupo** [comment]
everything is fine only last change can not apply.
