### ISSUE TITLE
Error when SMART values not available

### ISSUE THREAD

**Issue by Monthrect** [Corsinvest/cv4pve-diag#11]
My proxmox host has a PERCH700 RAID Card installed, with x8 HDD's plugged in, the SMART values have never been presented to the OS layer (because of the RAID) however can be checked via the RAID-card drivers.

That part isn't your problem, however your script shouldn't fail-out because SMART status can't be retrieved for disks. A softer error would be nice.

![image](https://github.com/Corsinvest/cv4pve-diag/assets/16352672/7c87b9ba-03e4-4d01-a4ca-34087c0a4fbc)

**Comment by franklupo** [comment]
Hi,
Did you  can run with --debug and attach log.
Remember remive passwor from log.

Best regards

**Comment by franklupo** [comment]
News?

**Comment by franklupo** [comment]
News?
