### ISSUE TITLE
Image orphaned for EFI and TPM disks

### ISSUE THREAD

**Issue by mavhc** [Corsinvest/cv4pve-diag#5]
| local-zfs:vm-101-disk-2 | Image Orphaned                                               | Storage | Image        | Warning  |
| local-zfs:vm-101-disk-3 | Image Orphaned                                               | Storage | Image        | Warning  |

These are EFI and TPM state disks

**Comment by franklupo** [comment]
HI,
i found the problem for EFI. what is TMP?

best regards

**Comment by mavhc** [comment]
TPM, trusted platform module

**Comment by franklupo** [comment]
Fix in next release
