### ISSUE TITLE
NTP clients

### ISSUE THREAD

**Issue by mavhc** [Corsinvest/cv4pve-diag#6]
"Service 'systemd-timesyncd.service' not running"

https://pve.proxmox.com/wiki/Time_Synchronization

"As of Proxmox VE 7, chrony is used as the default NTP daemon, while Proxmox VE 6 uses systemd-timesyncd"

I suppose cv4pve-diag should check that one of the two is enabled, not both, and not neither.

**Comment by franklupo** [comment]
Fixed in new release
