### ISSUE TITLE
VirtIO info is not aligned with Proxmox docs

### ISSUE THREAD

**Issue by NovacomExperts** [Corsinvest/cv4pve-diag#7]
As a performance recommandation, using the diag I get many :

> For more performance switch 'scsi0' hdd to VirtIO

I am already on the type of controller the docs recommends :

> **A SCSI controller of type VirtIO SCSI is the recommended setting if you aim for performance** and is automatically selected for newly created Linux VMs since Proxmox VE 4.3. Linux distributions have support for this controller since 2012, and FreeBSD since 2014. For Windows OSes, you need to provide an extra iso containing the drivers during the installation. If you aim at maximum performance, you can select a SCSI controller of type VirtIO SCSI single which will allow you to select the IO Thread option. When selecting VirtIO SCSI single Qemu will create a new controller for each disk, instead of adding all disks to the same controller.
> 
> The VirtIO Block controller, often just called VirtIO or virtio-blk, is an older type of paravirtualized controller. It has been superseded by the VirtIO SCSI Controller, in terms of features.
> 

Maybe cv2pve-diag is still validating for the old VirtIO Block controller ?

**Comment by franklupo** [comment]
Hi, 
add config vm so I analyze the problem. 

Best Regards
