### ISSUE TITLE
CV4PVE-DIAG Debian Bash Command Not Found

### ISSUE THREAD

**Issue by kenrmayfield** [Corsinvest/cv4pve-diag#9]
Frank,

I did try the CV4PVE-DIAG in Debian however the Error:
-bash: cv4pve-diag: command not found

The Syntax I used:
root@CV4PVEDIAGDebian:/cv4pvediag# cv4pve-diag --output=Text --host=10.0.0.1:8006 --username=root@pam --password=password execute

Proof the Command is in the Directory /cv4pvediag:
root@CV4PVEDIAGDebian:/cv4pvediag# ls
cv4pve-diag
root@CV4PVEDIAGDebian:/cv4pvediag#

**Comment by franklupo** [comment]
Hi,
did you download the latest version and unzip it?

**Comment by kenrmayfield** [comment]
@matteocv

Frank,

Yes, I used the Latest Version.

**Comment by franklupo** [comment]
hi,
i tried and everything works

```sh
frank# wget https://github.com/Corsinvest/cv4pve-diag/releases/download/v1.4.8/cv4pve-diag-linux-x64.zip
frank# unzip cv4pve-diag-linux-x64.zip
frank# chmod +x ./cv4pve-diag

frank# ./cv4pve-diag
Required command was not provided.
Option '--host' is required.

Description:

     ______                _                      __
    / ____/___  __________(_)___ _   _____  _____/ /_
   / /   / __ \/ ___/ ___/ / __ \ | / / _ \/ ___/ __/
  / /___/ /_/ / /  (__  ) / / / / |/ /  __(__  ) /_
  \____/\____/_/  /____/_/_/ /_/|___/\___/____/\__/


  Diagnostic for Proxmox VE                      (Made in Italy)

  cv4pve-diag is a part of suite cv4pve.
  For more information visit https://www.corsinvest.it/cv4pve

Usage:
  cv4pve-diag [command] [options]

Options:
  --api-token <api-token>                            Api token format 'USER@REALM!TOKENID=UUID'. Require Proxmox VE 6.2
                                                     or later
  --username <username>                              User name <username>@<realm>
  --password <password>                              The password. Specify 'file:path_file' to store password in file.
  --host <host> (REQUIRED)                           The host name host[:port],host1[:port],host2[:port]
  --settings-file <settings-file>                    File settings (generated from create-settings)
  --ignored-issues-file <ignored-issues-file>        File ignored issues (generated from create-ignored-issues)
  --ignored-issues-show                              Show second table with ignored issue
  -o, --output <Html|Json|JsonPretty|Markdown|Text>  Type output [default: Text]
  --version                                          Show version information
  -?, -h, --help                                     Show help and usage information

Commands:
  create-settings        Create file settings (settings.json)
  create-ignored-issues  Create File ignored issues (ignored-issues.json)
  export-collect         Export collect data collect to data.json
  execute                Execute diagnostic and print result to console
```

best regards

**Comment by kenrmayfield** [comment]
@matteocv

Frank,

Go back and look at my First Posting about this.

I noticed you did a **chmod +x** cv4pve-diag on the Script.  There is nothing in the Instructions do Run **chmod +x** cv4pve-diag on the Script.

This is Not Listed in the Instructions.

There needs to be a **Pull Request** on this as well.

1.  The Syntax for cv4pve-diag [command] [options] **should be cv4pve-diag  [options] [command]**
     **Example:**  cv4pve-diag --output=Text --host=10.0.0.1:8006 --username=root@pam --password=password execute
2.  The **chmod +x** cv4pve-diag needs to be Added to the Instructions to make it a Executable
3.  Letting the User know to use **./** cv4pve-diag to Run the Script.   
     **NOTE:**  Some Users from the Windows World would not know to use **./** to Run the Script.   
                                                                               
Everything is Working now.  Excellent Tool by the way.
Exporting to HTML is Excellent as well. After I Exported the HTML Results and viewed through my Browser,
I was really Impressed not having to Click On the TASK History in Proxmox for each VM or Container to check for problems.

**Comment by franklupo** [comment]
HI,
see the [cv4pve-admin](https://github.com/Corsinvest/cv4pve-admin) is a Web Gui

Best reagrds

**Comment by kenrmayfield** [comment]
@matteocv

Frank,

Do Not Close just yet.  I am going to do a Pull Request on this also.


What did you mean by your last message: see the cv4pve-admin is a Web Gui
I do not understand what you are tring to say?

cv4pve-diag and cv4pve-admin are two different Programs.  Yes I already know cv4pve-admin is a web gui.

cv4pve-diag is alot faster still to pull diagnostic of your proxmox hypervisor due to the fact not having to Click On each Listing in cv4pve-admin to check for problems on each VM or Container.  You have to do the same thing in Proxmox when viewing TASK HISTORY.

**Comment by franklupo** [comment]
cv4pve-admin containg diagnostic scheduling with notification via mail.

**Comment by kenrmayfield** [comment]
@matteocv

Frank,

I have Completed a Pull Request.
